# Generated by Django 2.2.3 on 2019-08-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_profilemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='slug',
        ),
    ]
