# Generated by Django 2.2.3 on 2019-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_profilemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
