# Generated by Django 2.2.3 on 2019-08-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20190807_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='slug',
        ),
    ]
