# Generated by Django 2.2.3 on 2019-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_profilemodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='slug',
            new_name='name',
        ),
    ]
