# Generated by Django 2.2.3 on 2019-08-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_remove_profilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
    ]
