# Generated by Django 2.2.3 on 2019-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_remove_profilemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
