# Generated by Django 2.2.3 on 2019-08-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_auto_20190807_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
