# Generated by Django 2.2.3 on 2019-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0018_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
