# Generated by Django 2.2.3 on 2019-08-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0019_profilemodel_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='name',
            new_name='description',
        ),
    ]
