# Generated by Django 2.2.3 on 2019-08-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0020_auto_20190808_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
