# Generated by Django 2.2.3 on 2019-08-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0023_auto_20190812_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.PostModel'),
        ),
    ]
