# Generated by Django 2.2.3 on 2019-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0026_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
