# Generated by Django 2.2.3 on 2019-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0028_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
