# Generated by Django 2.2.3 on 2019-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShots', '0003_auto_20190807_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
