# Generated by Django 2.2.3 on 2019-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShots', '0007_aboutmodel_aboutteam_teamicon_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
