# Generated by Django 2.2.3 on 2019-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShots', '0008_teammodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
